### ISSUE TITLE
Make error highlighting in Jetbrains IDEs consistent with Nord styling

### ISSUE THREAD

**Issue by mtyn** [mtyn/polar#10]
The error highlighting in the Jetbrains IDE theme is currently a red background with black text, in the original Nord theme it is a more subtle yet still clear red text with a plain background. The styling in Polar is inconsistent with the styling of the rest of the theme and needs updating.

**Comment by Kernald** [comment]
This is especially problematic when there are undefined/not yet indexed/generated symbols that also appear in red. Both the foreground and background colours end up the same red, which makes it quite tricky :-)
![Screenshot from 2021-05-21 11-50-34](https://user-images.githubusercontent.com/296840/119070189-d7644e80-ba2a-11eb-92ab-d9197ce99951.png)
