### ISSUE TITLE
Update all themes to better match the original Nord guidelines

### ISSUE THREAD

**Issue by mtyn** [mtyn/polar#4]
Currently the colours and themes were my best guess as to how to convert the Nord themes to a light variant. However many of the colour choices are not quite right, or use the wrong colours for various syntax elements in the IDE themes. Some of them are missing colours altogether.

To fix this, the colours should be adjusted so they match the original Nord specification as closely as possible.

Todo List:
- [x] Fix the background colour to allow other elements to be more readable
- [x] Change colours from the original Nord frost/aurora palettes back to their original colours, rather than my adjusted shades which are not as good!
- [x] Ensure, in syntax themes, that the correct colours are used for the correct elements.

**Comment by mtyn** [comment]
Todo list for this issue added to main comment

**Comment by derekschinke** [comment]
Did this ever get accomplished? I want to use this, but its inconsistencies with the Nord palette prevent me from doing so

**Comment by mtyn** [comment]
This is in progress! I've been a bit distracted lately so I hadn't made as much progress as I'd hoped, but I'm getting there and it shouldn't be too much longer. Sorry about the delay!

**Comment by mtyn** [comment]
Just out of curiosity, one of the things I was going to do as part of this was to lighten the background colour in the terminal/editor themes as it was quite hard to read some of the Nord colours on the lightest snow storm colour - I'm thinking a slightly off-white. 

Does this go too much against using only Nord colours? Without doing this it might make some of the themes less pleasant to use, and I believe the original Nord developer mentioned this might be necessary when working on a light theme? Interested in getting people's opinions so we end up with something we're all happy with using!

**Comment by derekschinke** [comment]
I think even [nordtheme.com](https://www.nordtheme.com/) uses colors outside of the palette (I notice `#fff` and a darker color than `nord0`) so I think it's fine.

Or, maybe even using `nord4` or `nord5` would work? I tried to adapt the Nord theme to using these colors, with some success, but it needs more tweaking.

**Comment by mtyn** [comment]
I've been trialling `#FAFAFE` as a bluish off-white background for a while, which seems to work nicely with the other normal Nord colours. I think personally even the brightest snow storm colours have been too dark to work well with some other the lighter colours (especially the yellow and green shades). I'll go with that for now - once I've committed the changes if it doesn't work out I'm happy to try some other options. 

There's even the option of doing a few different versions - pure Nord palette, a white/off-white background, or something else entirely. Just changing the background colour isn't too much work to try some different things.

**Comment by mtyn** [comment]
I've pushed the terminal files I have already / I could do quickly. The IDE / editor changes will take a little longer.

**Comment by derekschinke** [comment]
In Mac.terminal, it looks like it's using `#FBFBFE` instead of `#FAFAFE`

edit: it actually all still looks different from the original Nord palette

**Comment by mtyn** [comment]
Hmm, strange, the profile I exported it from is definitely using the Nord colours now. I'll investigate what happened!

**Comment by mtyn** [comment]
OK, so if I import the new profile I get the expected colours and background - can you verify you're trying the latest version of the terminal profile? I pushed the latest version just under half an hour ago, in commit `b9ff75a1`? If so then something strange is happening!

**Comment by derekschinke** [comment]
So, I think it might be a problem with Digital Color Meter.app, instead. The color profile in Terminal.app preferences is correct, but DCM.app gives me different values for what's displayed there, versus nordtheme.com, versus the palette in Pixelmator Pro. 🤷🏼‍♂️ Everything is assigned the correct values, but for some reason macOS is measuring their onscreen values strangely. My bad!

**Comment by mtyn** [comment]
No problem! Could it be due to Night Shift shifting the colours maybe?

Now those are working, I'll make a start on the IDEs/editors tomorrow.

**Comment by derekschinke** [comment]
One more quick thing regarding Terminal.app, do you think it should account for Normal and Bright ANSI variants like the Nord terminal theme does? It has 2 shades for ANSI black, cyan, and white

**Comment by mtyn** [comment]
Yeah I can do that - I'm making it a separate issue though (#7) as I think this ticket should be about fixing the themes that don't use Nord colours at all / use the old variant colours.

**Comment by mtyn** [comment]
Updated VSCode in 0aad8bf0452e47326b4281f3daf7da786b366d78 to use the original Nord colours. Slightly shifted the background colour to `#f9fafb` (a 70% lighter shade of the original Nord base Snow Storm colour) to make it more consistent - I'll update the terminal colours to match.

Edit: Terminal colours updated, and Xcode updated in 156f54b29b5711183ba0057e25a287321127d553 to match.

**Comment by mtyn** [comment]
With the completion of the JetBrains plugin in affb1bd6c9abb06512057fd9bc1a7f40960472bc , that should be everything possible up to date with the new styles. There'll probably be some small glitches, but these can be added as new issues.

Sidenote: The JetBrains IDE plugin will shortly be available on the plugin marketplace!
