### ISSUE TITLE
Vim theme comments aren't distinguishable from normal foreground text

### ISSUE THREAD

**Issue by brihadeesh** [mtyn/polar#6]
I just tried the vim theme on neovim (ver 0.3.8) and the comments per syntax highlighting aren't very easily distinguishable from non-comment text (see screenshot). I'm also using a couple of plugins for better syntax highlighting with markdown files although since it uses the as its base the colour-scheme applied. Perhaps make the comments lighter (as in colour7: bac3d6)?  The same goes for the line numbers which are apparently using default foreground colours?

This also looks like an extension of #4 

![polar_errors_1](https://user-images.githubusercontent.com/32803930/62533896-63f94900-b865-11e9-9d5a-5fef2d298eec.png)

**Comment by mtyn** [comment]
Yeah I've not given much attention to the vim theme recently sadly, as it's not a tool I use as often as some of the others. I'm going to be redoing a lot of the colours etc as part of #4, but I'll try and get in a fix for this in the meantime. Are there any other problem colours in the vim theme or is it mostly the comments? (asking as I've had some issues with other colours in the Jetbrains themes and if I'm making changes I might as well do any that need doing at the same time 😄)

**Comment by brihadeesh** [comment]
Afaik it's just the comments and the line numbers that aren't grey enough so to speak. I'm quite comfortable with the rest of the colours atleast for my use-case.

But if you're planning to change colours altogether this should perhaps be sorted.

**Comment by mtyn** [comment]
@ictinaetus I've altered the vim theme for now to respect the terminal colours, so hopefully if you're using the colour scheme for your terminal too that should be better colours being used. I'll get round to properly fixing the theme when I fix the colours for the other things too, but this should be a step in the right direction!

**Comment by mtyn** [comment]
Closing in favour of #4 , feel free to reopen if there's still problems with readability.
