### ISSUE TITLE
Colors in Jetbrains for Ruby and for ERB files look off

### ISSUE THREAD

**Issue by mariojackson** [mtyn/polar#9]
Hi,

first of all I want to say thank you for creating the theme. Nord is my favorite theme and I've missed a light one.
I've realized that some colors for Ruby and for ERB files look incorrect in Jetbrains IDE's. Please see the screenshot I've attached.

Thank you

Ruby
<img width="634" alt="image" src="https://user-images.githubusercontent.com/57389555/98930463-f5ca1a00-24dc-11eb-8810-cbe74e365d2f.png">

ERB
<img width="870" alt="image" src="https://user-images.githubusercontent.com/57389555/98930676-3fb30000-24dd-11eb-80f4-67fc350c3395.png">

**Comment by mtyn** [comment]
Thanks very much for reporting this, and glad you like the theme! I'll try to look into this as soon as I can, in the meantime as a workaround you should be able to adjust the colours manually in the colour scheme menu in Preferences -> Editor -> Color Scheme

**Comment by mariojackson** [comment]
I am going to do that for the meantime. 

Thank you for your quick response!

**Comment by mtyn** [comment]
Apologies for taking a while to get back to this. I've pushed an update (version 1.0.4) to the Polar theme in the JetBrains marketplace which should fix the problem with Ruby and ERB files. It might take a couple of days to be approved. If there's still problems once that's been installed, or it's not there by the start of next week, then feel free to reopen this issue.

**Comment by mariojackson** [comment]
No problem! I'm pretty sure that you have also got other things to do, so thank you for taking the time to resolve the issue.
